/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "MetronomeProcessor.h"

//==============================================================================
/** A demo synth sound that's just a basic sine wave.. */
class MetronomeSound : public SynthesiserSound
{
public:
    MetronomeSound() {}

    bool appliesToNote (const int /*midiNoteNumber*/)           { return true; }
    bool appliesToChannel (const int /*midiChannel*/)           { return true; }
};

//==============================================================================
/** A simple demo synth voice that just plays a sine wave.. */
class MatronomeVoice  : public SynthesiserVoice
{
public:
    MatronomeVoice()
        : angleDelta (0.0f),
          tailOff (0.1f)
    {
    }

    bool canPlaySound (SynthesiserSound* sound)
    {
        return dynamic_cast <MetronomeSound*> (sound) != 0;
    }

    void startNote (const int midiNoteNumber, const float velocity,
                    SynthesiserSound* /*sound*/, const int /*currentPitchWheelPosition*/)
    {
        tailOff = 1.0f;

    	currentAngle = 0.0f;
        level = velocity * 0.15f;

        double cyclesPerSecond = MidiMessage::getMidiNoteInHertz (midiNoteNumber);
        double cyclesPerSample = cyclesPerSecond / getSampleRate();

        angleDelta = cyclesPerSample * 2.0f * double_Pi;


		printf("START NOTE!");
    }

    void stopNote (const bool allowTailOff)
    {
        if (allowTailOff)
        {
            // start a tail-off by setting this flag. The render callback will pick up on
            // this and do a fade out, calling clearCurrentNote() when it's finished.

            if (tailOff == 0.0f) // we only need to begin a tail-off if it's not already doing so - the
                                // stopNote method could be called more than once.
                tailOff = 1.0f;
        }
        else
        {
            // we're being told to stop playing immediately, so reset everything..

            clearCurrentNote();
            angleDelta = 0.0f;
        }
    }

    void pitchWheelMoved (const int /*newValue*/)
    {
        // can't be bothered implementing this for the demo!
    }

    void controllerMoved (const int /*controllerNumber*/, const int /*newValue*/)
    {
        // not interested in controllers in this case.
    }

    void renderNextBlock (AudioSampleBuffer& outputBuffer, int startSample, int numSamples)
    {
        if (angleDelta != 0.0f)
        {
            if (tailOff > 0)
            {
                while (--numSamples >= 0)
                {
                    const float currentSample = (float) (sin (currentAngle) * level * tailOff);

                    for (int i = outputBuffer.getNumChannels(); --i >= 0;)
                        *outputBuffer.getSampleData (i, startSample) += currentSample;

                    currentAngle += angleDelta;
                    ++startSample;

                    tailOff *= 0.9998f;

                    if (tailOff <= 0.005f)
                    {
                        clearCurrentNote();

                        angleDelta = 0.0f;
                        break;
                    }
                }
            }
            else
            {
                while (--numSamples >= 0)
                {
                    const float currentSample = (float) (sin (currentAngle) * level);

                    for (int i = outputBuffer.getNumChannels(); --i >= 0;)
                        *outputBuffer.getSampleData (i, startSample) += currentSample;

                    currentAngle += angleDelta;
                    ++startSample;
                }
            }
        }
    }

private:
    double currentAngle, angleDelta, level, tailOff;
};


//==============================================================================
MetronomeProcessor::MetronomeProcessor()
{
    // Set up some default values..
    currentVolume = 1.0f;

    // we only need one voice
    synth.addVoice (new MatronomeVoice());
    synth.addSound (new MetronomeSound());
}

MetronomeProcessor::~MetronomeProcessor()
{
}

//==============================================================================
int MetronomeProcessor::getNumParameters()
{
    return totalNumParams;
}

float MetronomeProcessor::getParameter (int index)
{
    // This method will be called by the host, probably on the audio thread, so
    // it's absolutely time-critical. Don't use critical sections or anything
    // UI-related, or anything at all that may block in any way!
    switch (index)
    {
        case volumeParam:     return currentVolume;
        default:            return 0.0f;
    }
}

void MetronomeProcessor::setParameter (int index, float newValue)
{
    // This method will be called by the host, probably on the audio thread, so
    // it's absolutely time-critical. Don't use critical sections or anything
    // UI-related, or anything at all that may block in any way!
    switch (index)
    {
        case volumeParam:     currentVolume = newValue;  break;
        default:            break;
    }
}

const String MetronomeProcessor::getParameterName (int index)
{
    switch (index)
    {
        case volumeParam:     return "volume";
        default:            break;
    }

    return String::empty;
}

const String MetronomeProcessor::getParameterText (int index)
{
    return String (getParameter (index), 2);
}

//==============================================================================
void MetronomeProcessor::prepareToPlay (double sampleRate, int /*samplesPerBlock*/)
{
    // Use this method as the place to do any pre-playback
    // initialisation that you need..
    synth.setCurrentPlaybackSampleRate (sampleRate);
}

void MetronomeProcessor::releaseResources()
{

}

void MetronomeProcessor::reset()
{

}

void MetronomeProcessor::processBlock (AudioSampleBuffer& buffer, MidiBuffer& midiMessages)
{
    const int numSamples = buffer.getNumSamples();
    int channel;

	// convert special metronome bip and bop (0xf2 00 and 0xf2 01) into note on/off messages

	MidiBuffer metronomeMidiBuffer;
	MidiBuffer::Iterator iter(midiMessages);
	MidiMessage message;
	int pos;
	while (iter.getNextEvent(message,pos))
	{
		if (message.getRawDataSize()==2 && message.isSongPositionPointer())
		{
			char raw[4] = {0,0,0,0};

			char* data = (char*)message.getRawData();
			if (data[1]==0)
			{
				// bip
				MidiMessage b = MidiMessage::noteOn(1,80,64.0f);
				memcpy(raw,b.getRawData(),4);
			}
			else
			{
				// bop
				MidiMessage b = MidiMessage::noteOn(1,70,64.0f);
				memcpy(raw,b.getRawData(),4);
			}

			if (raw[0])
			{
				MidiMessage m(raw[0],raw[1],raw[2]);
				printf("m %d %d %d at %d\n",m.getRawData()[0],m.getRawData()[1],m.getRawData()[2],pos);

				// TODO: make it so we dont need a noteoff, to remove hack below
				// metronome is one audio sample ahead so we can easily do a noteoff
				metronomeMidiBuffer.addEvent(m,pos==0?1:pos);
			}
		}
	}

    // and now get the synth to process these midi events and generate its output.
    synth.renderNextBlock (buffer, metronomeMidiBuffer, 0, numSamples);
}

//==============================================================================
void* MetronomeProcessor::createEditor()
{
    return nullptr;
}

//==============================================================================
void MetronomeProcessor::getStateInformation (MemoryBlock& destData)
{

}

void MetronomeProcessor::setStateInformation (const void* data, int sizeInBytes)
{

}

const String MetronomeProcessor::getInputChannelName (const int channelIndex) const
{
    return String (channelIndex + 1);
}

const String MetronomeProcessor::getOutputChannelName (const int channelIndex) const
{
    return String (channelIndex + 1);
}

bool MetronomeProcessor::isInputChannelStereoPair (int /*index*/) const
{
    return true;
}

bool MetronomeProcessor::isOutputChannelStereoPair (int /*index*/) const
{
    return true;
}

bool MetronomeProcessor::acceptsMidi() const
{
	return true;
}

bool MetronomeProcessor::producesMidi() const
{
	return false;
}

bool MetronomeProcessor::silenceInProducesSilenceOut() const
{
    return false;
}

double MetronomeProcessor::getTailLengthSeconds() const
{
    return 0.0;
}

